backend/app/urls.py
# ----------------------------------------------------------------------
# Enterpriseviz
# Copyright (C) 2025 David C Jantz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------
from app.views import *
from django.urls import path

app_name = "enterpriseviz"

urlpatterns = [
    path(r"/table/<name>/", Table.as_view(), name="table"),
    path(r"/table/<instance>/<name>/", Table.as_view(), name="table"),
    path(r"/portal/add/", portal_create_view, name="add_portal"),
    path(r"/portal/delete/<instance>/", delete_portal_view, name="delete_portal"),
    path(r"/portal/update/<instance>/", update_portal_view, name="update_portal"),
    path(r"/portal/refresh/", refresh_portal_view, name="refresh_portal"),
    path(r"/portal/refresh/progress/<instance>/<task_id>/", progress_view, name="refresh_progress"),
    path(r"/login/", login_view, name="login"),
    path(r"/logout/", logout_view, name="logout"),
    path(r"/layer/<name>/", portal_layer_view, name="layer"),
    path(r"/portal/<instance>/service/<path:url>/", portal_service_view, name="service"),
    path(r"/portal/<instance>/map/<id>", portal_map_view, name="map"),
    path(r"/portal/schedule/<instance>/", schedule_task_view, name="schedule"),
    path(r"/portal/<instance>/duplicates/", duplicates_view, name="duplicate"),
    path(r"/portal/<instance>/layerid/", layerid_view, name="layerid"),
    path(r"/portal/<instance>/metadata/", metadata_view, name="metadata"),
    path(r"/portal/<instance>/", index_view, name="viz"),
    path(r"/theme", mode_toggle_view, name="mode_toggle"),
    path(r"/usage", usage_toggle_view, name="usage_toggle"),
    path(r"/webhook", webhook_view, name="webhook"),
    path(r"/settings/email/", email_settings, name="email_settings"),
    path(r"/settings/logs/", log_settings_view, name='log_settings'),
    path(r"/logs/", logs_view, name="log"),
    path(r"/logs/table/", LogTable.as_view(), name="log_table"),
    path(r"/notify/", notify_view, name="notify"),
    path(r"/portal/tools/<instance>/", tool_settings, name="tool_settings"),
    path(r"/portal/tools/<instance>/<tool_name>/", tool_run, name="tools_run"),
    path(r"/settings/webhook/", webhook_settings_view, name='webhook_settings'),

    # The home page
    path(r"/", index_view, name="index"),
]

backend/app/templates/app/base_site.html
<!--
    Enterpriseviz
    Copyright (C) 2025 David C Jantz

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
-->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  {% block head %}
    {% block meta %}
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="htmx-config"
            content='{"refreshOnHistoryMiss":"true","useTemplateFragments": true,"includeIndicatorStyles": false}'>

      <!-- Meta, title, CSS, favicons, etc. -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" type="image/icon" href="{% static 'build/favicon.ico' %}">
    {% endblock meta %}

    <title>EnterpriseViz! | {% block title %}{% endblock %}</title>

    {% block stylesheets %}
      <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
      <link href="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.7.0/moment-2.29.4/dt-2.3.2/datatables.min.css"
            rel="stylesheet" integrity="sha384-UV+xWD66eGkqXI992kNH1GTvdpKW/D/WfOXL57DaViVRbnlga+tiQUI+C7fSOSU0"
            crossorigin="anonymous">
      <link href="https://cdn.datatables.net/v/dt/jszip-3.10.1/b-3.2.3/b-html5-3.2.3/b-print-3.2.3/datatables.min.css"
            rel="stylesheet" integrity="sha384-y/Ggch3BSjw9RT0Hmyt6sKycej5an0TFUOmufQwHfSh4KW47j9bBITxrpLV1H1oB"
            crossorigin="anonymous">


      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"/>
      <!-- ArcGIS JavaScript API-->
      {% if user.profile.mode == 'dark' %}
        <link id="arcgis-maps-sdk-theme-dark" rel="stylesheet"
              href="https://js.arcgis.com/4.32/esri/themes/dark/main.css"/>
      {% else %}
        <link disabled id="arcgis-maps-sdk-theme-dark" rel="stylesheet"
              href="https://js.arcgis.com/4.32/esri/themes/dark/main.css"/>
      {% endif %}
      <link id="arcgis-maps-sdk-theme-light" rel="stylesheet"
            href="https://js.arcgis.com/4.32/esri/themes/light/main.css"/>
    {% endblock stylesheets %}
    <!-- Custom Theme Style -->
    <link href="{% static '/build/css/custom.css' %}" rel="stylesheet">
  {% endblock head %}
</head>
<div id="mode" mode="{{ user.profile.mode }}"></div>
{% if user.profile.mode == 'dark' %}
  <body class="calcite-mode-dark"
        hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-ext="loading-states">
{% else %}
  <body class="calcite-mode-light"
        hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-ext="loading-states">
{% endif %}
{% block body %}

  <div>
    <calcite-shell>
      <calcite-navigation slot="header">
        <calcite-progress slot="progress" type="indeterminate" id="loading" data-loading loading
                          data-loading-delay label="Loading content" role="status" aria-live="polite"
                          aria-atomic="true"></calcite-progress>
        <calcite-navigation-logo slot="logo" heading="EnterpriseViz"
                                 icon="map-pin" preload="true">
        </calcite-navigation-logo>
        <calcite-navigation-user id="nav-user" slot="user" full-name="{{ user.get_full_name }}"
                                 username="{{ user.get_username }}" label="User Menu"></calcite-navigation-user>
      </calcite-navigation>
      <calcite-shell-panel slot="panel-start" position="start" id="shell-panel-start" display-mode="overlay"
                           collapsed
                           width="m" label="Navigation panel">
        <calcite-action-bar slot="action-bar" label="Main navigation">
          <calcite-action id="home" icon="home" text="Home" label="Home"
                          hx-get="{% url 'enterpriseviz:index' %}" hx-target="#mainbodycontent"
                          hx-push-url="{% url 'enterpriseviz:index' %}"></calcite-action>
          <calcite-action id="portals" data-action-id="portals" icon="all-servers" text="Portals"
                          label="Portals"></calcite-action>

          <calcite-action-group slot="actions-end">
            <calcite-action id="manage" data-action-id="manage" text="Manage" icon="system-management"
                            label="Manage"></calcite-action>
            <calcite-action data-action-id="settings" id="settings" text="Settings" icon="gear"
                            label="Settings"></calcite-action>
          </calcite-action-group>
          <calcite-tooltip slot="expand-tooltip"><span>Toggle Action Bar</span></calcite-tooltip>
        </calcite-action-bar>

        <calcite-panel heading="Portals" height-scale="m" data-panel-id="portals" hidden>
          {% include 'app/portal_panel.html' %}
        </calcite-panel>
        {% if user.is_superuser %}
          <calcite-panel heading="Manage" data-panel-id="manage" hidden>
            {% include 'app/manage_panel.html' %}
            <calcite-fab scale="m" text-enabled text="Add Portal" icon="plus" slot="fab"
                         id="add-portal" hx-get="{% url 'enterpriseviz:add_portal' %}" hx-trigger="click"
                         hx-target="#add_portal_modal" label="Add Portal">
            </calcite-fab>
          </calcite-panel>
        {% endif %}
        <calcite-panel heading="Settings" data-panel-id="settings" hidden>
          {% include 'app/settings_panel.html' %}
        </calcite-panel>
      </calcite-shell-panel>
      <calcite-panel id="main-content-panel">
        <div id="mainbodycontent" hx-history-elt hidden role="main" aria-live="polite">
          {% block content %}
          {% endblock content %}
        </div>
      </calcite-panel>

    </calcite-shell>
    <calcite-tooltip reference-element="home" placement="left" overlay-positioning="fixed" close-on-click>
      <span>Home</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="portals" placement="left" overlay-positioning="fixed" close-on-click>
      <span>Change the selected portal</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="manage" placement="left" overlay-positioning="fixed" close-on-click>
      <span>Update and delete portals. Schedule automatic updates.</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="settings" placement="left" overlay-positioning="fixed" close-on-click>
      <span>Change user settings</span>
    </calcite-tooltip>
    <div id="email_settings_modal"></div>
    <div id="add_portal_modal"></div>
    <div id="update_portal_modal" hx-target="this"></div>
    <div id="schedule_portal_modal" hx-target="this"></div>
    <div id="tool_settings_modal" hx-target="this"></div>
    <div id="webhook_settings_modal"></div>
    <div id="alert-container" hx-target="this" role="alert" aria-live="polite" aria-atomic="true"></div>
    <calcite-popover label="User navigation menu" reference-element="nav-user" placement="bottom" pointer-disabled
                     scale="s" auto-close>
      <p class="padding-1-6-0 margin-0"></p>
      <calcite-button kind="neutral" scale="s" icon-start="user" class="margin-0-12-12" label="Profile">
        Profile
      </calcite-button>
      {% if user.is_superuser %}
        <calcite-button kind="neutral" scale="s" icon-start="dashboard" class="margin-0-12-12"
                        href="/enterpriseviz/admin/" label="Admin">
          Admin
        </calcite-button>
      {% endif %}
      {% if user.is_authenticated %}
        <calcite-button kind="neutral" scale="s" icon-start="sign-out" class="margin-0-12-12"
                        href="/enterpriseviz/logout/" label="Sign Out">
          Sign-Out
        </calcite-button>
      {% else %}
        <calcite-button kind="neutral" scale="s" icon-start="sign-in" class="margin-0-12-12"
                        href="/enterpriseviz/login/" label="Sign In">
          Sign-In
        </calcite-button>
      {% endif %}
    </calcite-popover>
  </div>
  {% if user.is_superuser %}
  <!-- Reusable Delete Confirmation Sheet -->
  <calcite-sheet label="Confirm Deletion" position="block-end" display-mode="float" id="delete-confirm-sheet"
                 height="s" width="s" class="delete-confirm-sheet">
    <calcite-panel heading="Confirm Deletion" heading-level="2">
      <calcite-notice open kind="danger" icon="exclamation-mark-triangle" width="full">
        <div slot="title">
          <div id="delete-confirm-message">Are you sure you want to proceed with this deletion?</div>
        </div>
        <div slot="message">
          <div id="delete-confirm-details"></div>
        </div>
      </calcite-notice>

      <div class="delete-confirm-buttons">
        <calcite-button id="delete-confirm-yes" width="full" kind="danger" icon-start="trash"
                        label="Confirm deletion">
          Delete
        </calcite-button>
        <calcite-button id="delete-confirm-no" width="full" kind="neutral" appearance="outline"
                        label="Cancel deletion">
          Cancel
        </calcite-button>
      </div>
    </calcite-panel>
  </calcite-sheet>
  {% endif %}
{% endblock body %}
</body>
{% block javascripts %}

  <!-- HTMX-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/2.0.4/htmx.min.js"
          integrity="sha512-2kIcAizYXhIn8TzUvqzEDZNuDZ+aW7yE/+f1HJHXFjQcGNfv1kqzJSTBRBSlOgp6B/KZsz1K0a3ZTqP9dnxioQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://unpkg.com/htmx-ext-loading-states@2.0.0/loading-states.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"
          integrity="sha384-VFQrHzqBh5qiJIU0uGU5CIW3+OWpdGGJM9LBnGbuIH2mkICcFZ7lPd/AAtI7SNf7"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"
          integrity="sha384-/RlQG9uf0M2vcTw3CX7fbqgbj/h8wKxw7C3zu9/GxcBPRKOEcESxaxufwRXqzq6n"
          crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.7.0/moment-2.29.4/dt-2.3.2/datatables.min.js"
          integrity="sha384-WYiics5laGr3Jd9e4qVSKEHgHc69E4lK0MNvP2iQ15tmZ22VAn8VHEvJqmf07aug"
          crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/v/dt/jszip-3.10.1/b-3.2.3/b-html5-3.2.3/b-print-3.2.3/datatables.min.js"
          integrity="sha384-SJmtIMnPBDCgAvXzJCCf+5OJ73T9jcArW23qCu2tu//NbXPpeH80s6suOmvfZ+LL"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"
          integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
          crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/plug-ins/1.13.4/sorting/datetime-moment.js"></script>

  <script type="module" src="https://js.arcgis.com/calcite-components/3.3.3/calcite.esm.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/d3@3.0.0/d3.min.js"
          integrity="sha256-b69VTDu5tPmoLspoBD0rxTFiimxoTONDLrAgF68zU8c=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-autocolors"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@^1"></script>
  <script src="{% static 'build/js/cytoscape-dependency-graph.js' %}"></script>
  <script src="{% static 'build/js/custom.js' %}"></script>
  <script src="{% static 'build/js/history-preserve-extension.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.33.1/cytoscape.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/dagre/0.8.5/dagre.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/cytoscape-dagre@2.5.0/cytoscape-dagre.min.js"></script>

{% endblock javascripts %}
</html>

backend/app/templates/app/login.html
<!-- Licensed under GPLv3 - See LICENSE file for details. -->

{% extends "app/base_site.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block body_class %}login{% endblock body_class %}

{% block body %}
  <calcite-dialog open modal close-disabled escape-disabled outside-close-disabled id="login-modal" heading="Login"
                  width="s" label="Login to EnterpriseViz">
    <img src="https://raw.githubusercontent.com/Esri/calcite-ui-icons/master/icons/map-pin-32.svg"
         slot="header-actions-end" class="login-header-img"
         draggable="false" alt="EnterpriseViz logo">

    <div class="login-content-container">

      <calcite-block open collapsible heading="Use your organization URL"
                     description="Sign in with your ArcGIS organization">
        <form>
          <calcite-input placeholder="{{ login_url }}" read-only label="Organization URL"
                         value="{{ login_url }}"></calcite-input>
          <calcite-button width="full" href="{% url 'social:begin' 'arcgis' %}"
                          label="Continue with organization login">
            Continue
          </calcite-button>
        </form>
      </calcite-block>

      <calcite-block collapsible heading="Use your credentials" description="Sign in with username and password">
        <form id="login_form" method="post" autocomplete="off" aria-label="Login form">
          {% csrf_token %}
          <calcite-input type="text" icon="user" id="{{ form.username.name }}" name="{{ form.username.name }}"
                         placeholder="{{ form.username.label }}" autocomplete="username"
                         label-text="Username" required
                         status="{% if form.username.errors %}invalid{% else %}idle{% endif %}"
                         validation-message="{{ form.username.errors|join:' ' }}"
                         validation-icon="{% if form.username.errors %}exclamation-mark-triangle{% endif %}"></calcite-input>

          <calcite-input type="password" icon="lock" id="{{ form.password.name }}" name="{{ form.password.name }}"
                         placeholder="{{ form.password.label }}" autocomplete="current-password"
                         label-text="Password" required
                         status="{% if form.password.errors %}invalid{% else %}idle{% endif %}"
                         validation-message="{{ form.password.errors|join:' ' }}"
                         validation-icon="{% if form.password.errors %}exclamation-mark-triangle{% endif %}"></calcite-input>

          {% if form.non_field_errors %}
            <calcite-notice open icon kind="danger">
              <div slot="message">{{ form.non_field_errors|join:" " }}</div>
            </calcite-notice>
          {% endif %}

          <calcite-button type="submit" form="login_form" width="full" label="Sign In">Sign in</calcite-button>
        </form>
      </calcite-block>

    </div>

  </calcite-dialog>
{% endblock body %}

backend/app/templates/app/logs_full.html
{% extends "app/base_site.html" %}

{% block content %}

    {% include 'app/logs.html' %}

{% endblock content %}

backend/app/templates/app/manage_panel.html
<!-- Licensed under GPLv3 - See LICENSE file for details. -->
<div id="manage-container" role="region" aria-label="Portal management">
  {% for item in portal %}
    <calcite-block heading="{{ item.0 }}" description="{{ item.2 }}">
      <calcite-icon scale="s" preload="true" slot="icon"
                    {% if item.1 == 'portal' %}icon="portal"
                    {% else %}icon="arcgis-online"{% endif %}
                    aria-hidden="true"></calcite-icon>
      <calcite-action id="manage-modal-delete-{{ item.0|slugify }}" slot="header-menu-actions"
                      text="Delete" text-enabled
                      icon="trash"
                      data-confirm-delete
                      data-delete-url="{% url 'enterpriseviz:delete_portal' instance=item.0 %}"
                      data-delete-target="#manage-container"
                      data-delete-message="Are you sure you want to delete &quot;{{ item.0 }}&quot;?"
                      data-delete-details="This will remove the portal and all associated data from EnterpriseViz."
                      data-delete-button="Delete Portal"
                      label="Delete {{ item.0 }}"></calcite-action>
      <calcite-action id="manage-modal-update-{{ item.0|slugify }}" slot="header-menu-actions"
                      text="Update" text-enabled
                      icon="refresh" hx-get="{% url 'enterpriseviz:update_portal' instance=item.0 %}"
                      hx-target="#update_portal_modal"
                      label="Update credentials for {{ item.0 }}"></calcite-action>
      <calcite-action id="manage-modal-schedule-{{ item.0|slugify }}" slot="header-menu-actions"
                      text="Schedule" text-enabled
                      icon="date-time" hx-get="{% url 'enterpriseviz:schedule' instance=item.0 %}"
                      hx-target="#schedule_portal_modal"
                      label="Schedule automatic updates for {{ item.0 }}"></calcite-action>
      <calcite-action id="manage-modal-tools-{{ item.0|slugify }}" slot="header-menu-actions"
                      text="Tools" text-enabled
                      icon="hammer" hx-get="{% url 'enterpriseviz:tool_settings' instance=item.0 %}"
                      hx-target="#tool_settings_modal"
                      label="Run administration tools for {{ item.0 }}"></calcite-action>

    </calcite-block>
    <calcite-tooltip reference-element="manage-modal-delete-{{ item.0|slugify }}" placement="right"
                     overlay-positioning="fixed" close-on-click>
      <span>Delete this portal from Enterpriseviz</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="manage-modal-update-{{ item.0|slugify }}" placement="right"
                     overlay-positioning="fixed" close-on-click>
      <span>Update credentials for this portal</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="manage-modal-schedule-{{ item.0|slugify }}" placement="right"
                     overlay-positioning="fixed" close-on-click>
      <span>Schedule automatic updates and view previous results</span>
    </calcite-tooltip>
    <calcite-tooltip reference-element="manage-modal-tools-{{ item.0|slugify }}" placement="right"
                     overlay-positioning="fixed" close-on-click>
      <span>Run portal administration tools</span>
    </calcite-tooltip>
  {% endfor %}
</div>

backend/app/templates/app/portal_panel.html
<!-- Licensed under GPLv3 - See LICENSE file for details. -->
<div id="portals-container" role="navigation" aria-label="Portal selection">
  {% for item in portal %}
    <calcite-action id="portal-{{ item.0|slugify }}" text="{{ item.0 }}"
                    {% if item.1 == 'portal' %}icon="portal"
                    {% else %}icon="arcgis-online"{% endif %}
                    text-enabled
                    {% if instance == item.0 %}active{% endif %}
                    hx-get="{% url 'enterpriseviz:viz' instance=item.0 %}"
                    hx-target="#mainbodycontent"
                    hx-push-url="{% url 'enterpriseviz:viz' instance=item.0 %}"
                    hx-swap="innerHTML show:top"
                    label="View {{ item.0 }} portal content"
                    {% if instance == item.0 %}aria-current="page"{% endif %}></calcite-action>

    <calcite-tooltip reference-element="portal-{{ item.0|slugify }}" placement="right"
                     overlay-positioning="fixed" close-on-click>
      <span>View content for {{ item.0 }}{% if item.2 %} - {{ item.2 }}{% endif %}</span>
    </calcite-tooltip>
  {% endfor %}
</div>

backend/app/templates/app/settings_panel.html
<!-- Licensed under GPLv3 - See LICENSE file for details. -->
<div id="settings-container" role="region" aria-label="Application settings">
  <calcite-action id="email-action" text="Email" icon="envelope" text-enabled
                  hx-get="{% url 'enterpriseviz:email_settings' %}"
                  hx-target="#email_settings_modal"
                  label="Configure email settings"></calcite-action>
  <calcite-action id="webhook-action" text="Webhook" icon="key" text-enabled
                  hx-get="{% url 'enterpriseviz:webhook_settings' %}"
                  hx-target="#webhook_settings_modal"
                  label="Configure webhook settings"></calcite-action>
  <calcite-action id="log-viewer-action" text="Logs" icon="access-string-results" text-enabled
                  hx-get="{% url 'enterpriseviz:log' %}"
                  hx-target="#mainbodycontent"
                  hx-push-url="true"
                  label="View application logs">
  </calcite-action>

  <calcite-tooltip reference-element="email-action" placement="left" overlay-positioning="fixed"
                   close-on-click>
    <span>Configure email settings for notifications</span>
  </calcite-tooltip>
  <calcite-tooltip reference-element="webhook-action" placement="left" overlay-positioning="fixed"
                   close-on-click>
    <span>Configure webhook settings for integrations</span>
  </calcite-tooltip>
  <calcite-tooltip reference-element="log-viewer-action" placement="left" overlay-positioning="fixed"
                   close-on-click>
    <span>View application logs and errors</span>
  </calcite-tooltip>

</div>

<div slot="content-bottom" class="width-full">
  <calcite-label layout="inline-space-between"
                 hx-post="{% url 'enterpriseviz:mode_toggle' %}"
                 hx-target="#mode-switch" hx-push-url="false">
    Theme:
    <calcite-icon icon="brightness" preload="true" scale="s" aria-hidden="true"></calcite-icon>
    <calcite-switch {% if user.profile.mode == 'dark' %}checked{% endif %}
                    id="mode-switch"
                    label="Toggle between light and dark theme"></calcite-switch>
    <calcite-icon icon="moon" preload="true" scale="s" aria-hidden="true"></calcite-icon>
  </calcite-label>
  <calcite-tooltip reference-element="mode-switch" placement="left" overlay-positioning="fixed"
                   close-on-click>
    <span>Switch between light and dark theme</span>
  </calcite-tooltip>

  <calcite-label layout="inline-space-between"
                 hx-post="{% url 'enterpriseviz:usage_toggle' %}"
                 hx-target="#usage-switch" hx-push-url="false">
    Service Usage:
    <calcite-icon icon="content-none" preload="true" scale="s" aria-hidden="true"></calcite-icon>
    <calcite-switch {% if user.profile.service_usage is True %}checked{% endif %}
                    id="usage-switch"
                    label="Toggle service usage graphs"></calcite-switch>
    <calcite-icon icon="graph-time-series" preload="true" scale="s" aria-hidden="true"></calcite-icon>
  </calcite-label>
  <calcite-tooltip reference-element="usage-switch" placement="left" overlay-positioning="fixed"
                   close-on-click>
    <span>Show or hide service usage graphs in dependency views</span>
  </calcite-tooltip>
</div>

<calcite-button kind="neutral" scale="m" icon-start="sign-out" slot="footer" width="full"
                href="{% url 'enterpriseviz:logout' %}" label="Sign out of EnterpriseViz">
  Sign-Out
</calcite-button>

backend/app/templates/app/sidebar.html
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet">

{% block sidebar_class %}
  <calcite-shell-panel slot="panel-start" display-mode="float">
    <calcite-action-bar slot="action-bar">
      <calcite-action icon="home" title="Home" text="Home" href="/enterpriseviz"></calcite-action>
    </calcite-action-bar>
  </calcite-shell-panel>
{% endblock sidebar_class %}